- name: copy docker-storage-setup to servers
  copy:
   src: docker-storage-setup
   dest: /etc/sysconfig/
   owner: root
   group: root
   mode: 0600

- name: restart docker service, and daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker