---
- name: "delete project {{ project }}"
  os_project:
    state: absent
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    name: "{{ project }}"
  ignore_errors: True

- name: delete user
  os_user:
    state: absent
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    name: "{{ app_user }}"
    domain: default
  ignore_errors: True

- name: delete image
  os_image:
    cloud: "{{ admin_cloud }}"
    name: "{{ app_image_name }}"
    state: absent
  ignore_errors: True

- name: "delete {{ project }}.lb"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.lb"
  ignore_errors: True

- name: "delete {{ project }}.master"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.master"
  ignore_errors: True

- name: "delete {{ project }}.infra"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.infra"
  ignore_errors: True

- name: "delete {{ project }}.node"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.node"
  ignore_errors: True

- name: "delete {{ project }}.nfs"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.nfs"
  ignore_errors: True

- name: "delete {{ project }}.bastion"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.bastion"
  ignore_errors: True
