---
- name: "delete project {{ project }}"
  os_project:
    state: absent
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    name: "{{ project }}"

- name: delete user
  os_user:
    state: absent
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    name: "{{ app_user }}"
    domain: default

- name: delete image
  os_image:
    cloud: "{{ admin_cloud }}"
    name: "{{ app_image_name }}"
    state: absent

- name: "delete '{{ project }}.standard' flavor with 8GB of RAM, 2 virtual CPUs, and a 50GB local disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.standard"

- name: "delete '{{ project }}.node' flavor with 16GB of RAM, 4 virtual CPUs, and a 50GB local disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: absent
    name: "{{project }}.node"