- lineinfile:
    path: /etc/origin/master/master-config.yaml
    regexp: '  networkPluginName: redhat/openshift-ovs-subnet'
    line: '  networkPluginName: "redhat/openshift-ovs-multitenant"'
  ignore_errors: True

- lineinfile:
    path: /etc/origin/node/node-config.yaml
    regexp: '  networkPluginName: redhat/openshift-ovs-subnet'
    line: '  networkPluginName: "redhat/openshift-ovs-multitenant"'
  ignore_errors: True

- name: restart master-api
  systemd:
    state: restarted
    daemon_reload: yes
    name: atomic-openshift-master-api.service
  ignore_errors: True

- name: restart master-controllers
  systemd:
    state: restarted
    daemon_reload: yes
    name: atomic-openshift-master-controllers.service
  ignore_errors: True

- name: restart atomic-openshift-node
  systemd:
    state: restarted
    daemon_reload: yes
    name: atomic-openshift-node.service
  ignore_errors: True

- name: restart openvswitch.service
  systemd:
    state: restarted
    daemon_reload: yes
    name: openvswitch.service
  ignore_errors: True