- lineinfile:
    path: /etc/origin/master/master-config.yaml
    backup: yes
    regexp: '  networkPluginName: "redhat/openshift-ovs-multitenant"'
    line: '  networkPluginName: "redhat/openshift-ovs-networkpolicy"'
  ignore_errors: True

- lineinfile:
    path: /etc/origin/node/node-config.yaml
    backup: yes
    regexp: '  networkPluginName: "redhat/openshift-ovs-multitenant"'
    line: '  networkPluginName: "redhat/openshift-ovs-networkpolicy"'
  ignore_errors: True

- name: reboot instances
  command: "reboot"
