- name: remove a key pair
  os_keypair:
    cloud: "{{ app_cloud }}"
    state: absent
    name: "{{ app_public_key }}"

- name: add a key pair
  os_keypair:
    cloud: "{{ app_cloud }}"
    endpoint_type: admin
    state: present
    name: "{{ app_public_key }}"
    public_key_file: "{{ remote_public_key }}"