---
- name: Delete a security group
  os_security_group:
    cloud: "{{ app_cloud }}"
    state: absent
    name: "{{ app_sec_grp }}"

- name: Delete router attached to openshift_ext_net  and one internal subnet interface.
  os_router:
    cloud: "{{ app_cloud }}"
    state: absent
    name: "{{ openstack_router }}"

- name: Get private subnet port facts
  os_port_facts:
    cloud: "{{ app_cloud }}"

- name: add port ids to fact list
  set_fact:
    ports: "{{ ports + [item.id] }}"
  with_items: "{{ openstack_ports }}"

- name: debug fact list
  debug:
    msg: "{{ ports  }}"

- name: delete ports
  os_port:
    state: absent
    cloud: "{{ app_cloud }}"
    name: "{{ item }}"
  with_items: "{{ ports }}"

- name: Delete private subnet
  os_subnet:
    state: absent
    cloud: "{{ app_cloud }}"
    network_name: "{{ openstack_int_net_name }}"
    name: "{{ openstack_int_subnet_name }}"

- name: Delete an private network
  os_network:
    cloud: "{{ app_cloud }}"
    state: absent
    name: "{{ openstack_int_net_name }}"

- name: Delete subnet on the external network
  os_subnet:
    state: absent
    cloud: "{{ admin_cloud }}"
    network_name: "{{ openstack_ext_net_name }}"
    name: "{{ openstack_ext_subnet_name }}"

- name: Delete an external network
  os_network:
    cloud: "{{ amin_cloud }}"
    state: absent
    name: "{{ openstack_ext_net_name }}"



