---
- hosts: openstack-server
  vars:
    ports: []
  remote_user: justin
  become: yes
  become_method: sudo
  tasks:
  - name: Delete a security group
    os_security_group:
      cloud: openshift_cloud
      state: absent
      name: openshift-sg
      description: security group for openshift servers

  - name: Delete router attached to openshift_ext_net  and one internal subnet interface.
    os_router:
      cloud: openshift_cloud
      state: absent
      name: openshift_router

  - name: Get private subnet port facts
    os_port_facts:
      cloud: openshift_cloud

  - name: add port ids to fact list
    set_fact:
      ports: "{{ ports + [item.id] }}"
    with_items: "{{ openstack_ports }}"

  - name: debug fact list
    debug:
      msg: "{{ ports  }}"

  - name: delete ports
    os_port:
      state: absent
      cloud: openshift_cloud
      name: "{{ item }}"
    with_items: "{{ ports }}"

  - name: Delete private subnet
    os_subnet:
      state: absent
      cloud: openshift_cloud
      network_name: openshift_int_net
      name: openshift_int_subnet

  - name: Delete an private network
    os_network:
      cloud: openshift_cloud
      state: absent
      name: openshift_int_net

  - name: Delete subnet on the external network
    os_subnet:
      state: absent
      cloud: default
      network_name: openshift_ext_net
      name: openshift_ext_subnet

  - name: Delete an external network
    os_network:
      cloud: default
      state: absent
      name: openshift_ext_net
      external: true
      provider_physical_network: extnet
      provider_network_type: flat



