---
- name: "Create an instance called {{ server_name }}"
  os_server:
    state: present
    cloud: "{{ app_cloud }}"
    wait: yes
    name: "{{ server_name }}"
    image: "{{ image_name }}"
    key_name: "{{ app_public_key }}"
    timeout: 200
    boot_from_volume: yes
    terminate_volume: yes
    flavor: "{{ server_flavour }}"
    security_groups: "{{ app_sec_grp }}"
    network: "{{ openstack_int_net_name }}"

- name: create a volume for docker
  os_volume:
    state: present
    cloud: "{{ app_cloud }}"
    size: "{{ docker_vol_size }}"
    display_name: "{{ server_name }}-docker-vol"

- name: "attach {{ server_name }}-docker-vol volume to {{ server_name }} instance"
  os_server_volume:
    state: present
    cloud: "{{ app_cloud }}"
    server: "{{ server_name }}"
    volume: "{{ server_name }}-docker-vol"
    device: /dev/vdb

