---
kind: Template
apiVersion: v1
metadata:
  name: user-template
  annotations:
    description: Template for creating an OpenShift user
    tags: user
labels:
  template: user
objects:
- kind: User
  apiVersion: v1
  metadata:
    name: "${USERNAME}"
  labels:
    level: admin
  identities:
  - htpasswd_auth:${USERNAME}
  groups: []
-kind: Identity
  metadata:
    name: htpasswd_auth:${USERNAME}
  providerName: htpasswd_auth
  providerUserName: ${USERNAME}
  user:
    name: ${USERNAME}
parameters:
- name: USERNAME
  description: Username of the OpenShift user
  required: true
