- name: make home for ssh keys
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: copy private key to servers
  copy:
   src: id_rsa
   dest: /root/.ssh/id_rsa
   owner: root
   group: root
   mode: 0600

- name: copy public key to servers
  copy:
   src: id_rsa.pub
   dest: /root/.ssh/id_rsa.pub
   owner: root
   group: root
   mode: 0600

- name: copy authorized_keys to servers
  copy:
   src: id_rsa.pub
   dest: /root/.ssh/authorized_keys
   owner: root
   group: root
   mode: 0600