- name: add rhel-7-server-rpms repo
  command: "subscription-manager repos --enable rhel-7-server-rpms"
  register: result
- debug:
    var: result.stdout

- name: add rhel-7-server-extras-rpms repo
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
  register: result
- debug:
    var: result.stdout

- name: add rhel-7-server-optional-rpms repo
  command: "subscription-manager repos --enable rhel-7-server-optional-rpms"
  register: result
- debug:
    var: result.stdout

- name: add rhel-7-server-ose-3.7-rpms repo
  command: "subscription-manager repos --enable rhel-7-server-ose-3.7-rpms"
  register: result
- debug:
    var: result.stdout

- name: add rhel-7-fast-datapath-rpms repo
  command: "subscription-manager repos --enable rhel-7-fast-datapath-rpms"
  register: result
- debug:
    var: result.stdout

- name: add epel repo
  command: "rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  register: result
  ignore_errors: True
- debug:
    var: result.stdout

- name: upgrade all packages
  yum:
    name: "*"
    state: latest