- name: add extras repo
  command: "subscription-manager repos --enable rhel-7-server-extras-rpms"
  register: result
- debug:
    var: result.stdout

- name: add optional repo
  command: "subscription-manager repos --enable rhel-7-server-optional-rpms"
  register: result
- debug:
    var: result.stdout

- name: add epel repo
  command: "rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  register: result
  ignore_errors: True
- debug:
    var: result.stdout