apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-registry-claim
spec:
  accessModes:
  - ReadWriteMany
  volumeName: gluster-registry-volume
  storageClassName: ""
  resources:
     requests:
       storage: 20Gi