apiVersion: v1
kind: Service
metadata:
  name: gluster-registry-service
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-registry-endpoints
subsets:
  - addresses:
      - ip: 192.168.0.132
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.0.139
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.0.141
    ports:
      - port: 1