---
- hosts: base-server
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - rhel_subscribe
  - sync_keys
  - install_repos
  - install_certs
  - install_tools

- hosts: openshift_cloud
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  gather_facts: no
  roles:
  - sync_keys
