---
- hosts: openstack-server
  vars:
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - { role: teardown_server, server_name: "{{ project }}-bastion"}
  - { role: teardown_server, server_name: "{{ project }}-master-lb"}
  - { role: teardown_server, server_name: "{{ project }}-lb1"}
  - { role: teardown_server, server_name: "{{ project }}-lb2"}
  - { role: teardown_server, server_name: "{{ project }}-master1"}
  - { role: teardown_server, server_name: "{{ project }}-master2"}
  - { role: teardown_server, server_name: "{{ project }}-master3"}
  - { role: teardown_server, server_name: "{{ project }}-node1"}
  - { role: teardown_server, server_name: "{{ project }}-node2"}
  - { role: teardown_server, server_name: "{{ project }}-infra1"}
  - { role: teardown_server, server_name: "{{ project }}-infra2"}
  - { role: teardown_server, server_name: "{{ project }}-nfs"}
  - { role: setup_server, server_name: "{{ project }}-bastion", image_name: "openshift-base", server_flavour: "{{ project }}.bastion", docker_vol_size: 5}
  - { role: setup_server, server_name: "{{ project }}-master-lb", image_name: "openshift-base", server_flavour: "{{ project }}.lb", docker_vol_size: 5}
  - { role: setup_server, server_name: "{{ project }}-lb1", image_name: "openshift-base", server_flavour: "{{ project }}.lb", docker_vol_size: 5}
  - { role: setup_server, server_name: "{{ project }}-lb2", image_name: "openshift-base", server_flavour: "{{ project }}.lb", docker_vol_size: 5}
  - { role: setup_server, server_name: "{{ project }}-master1", image_name: "openshift-base", server_flavour: "{{ project }}.master", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-master2", image_name: "openshift-base", server_flavour: "{{ project }}.master", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-master3", image_name: "openshift-base", server_flavour: "{{ project }}.master", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-infra1", image_name: "openshift-base", server_flavour: "{{ project }}.infra", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-infra2", image_name: "openshift-base", server_flavour: "{{ project }}.infra", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-node1", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}
  - { role: setup_server, server_name: "{{ project }}-node2", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}
  - { role: setup_server, server_name: "{{ project }}-nfs", image_name: "openshift-base", server_flavour: "{{ project }}.nfs", docker_vol_size: 5}

- hosts: localhost
  tasks:
  - name: pausing for 120 secs to allow servers to come up
    pause:
      seconds: 120

- hosts: openshift-servers
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - sync_keys

- hosts: openshift-docker-hosts
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - docker_config
