---
- hosts: openstack-server
  vars:
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - { role: teardown_server, server_name: "{{ project }}-node1"}
  - { role: teardown_server, server_name: "{{ project }}-node2"}
  - { role: teardown_server, server_name: "{{ project }}-master"}
  - { role: setup_server, server_name: "{{ project }}-master", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}
  - { role: setup_server, server_name: "{{ project }}-node1", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}
#  - { role: setup_server, server_name: "{{ project }}-node2", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}

- hosts: openshift_cloud
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - sync_keys

- hosts: openshift-servers
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - docker_config