---
- hosts: openstack-server
  vars:
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - setup_project
  - setup_network
#  - { role: setup_server, server_name: "{{ project }}-base", image_name: "{{ app_image_name }}", server_flavour: "{{ project }}.standard", docker_vol_size: 20}