---
- hosts: openstack-server
  vars:
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - setup_project
  - setup_network
  - { role: setup_server, server_name: "{{ project }}-ansible", image_name: "openshift-base", server_flavour: "{{ project }}.node", docker_vol_size: 100}

