---
- hosts: openshift-servers
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - file:
      path: /tmp/myhosts
      state: absent
    delegate_to: localhost

- hosts: openshift-servers
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
  - get_addresses
  tasks:
  - command: "cat /tmp/myhosts"
    delegate_to: localhost
    register: out
  - debug:
      var: out


