---
- hosts: openshift_cloud
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  serial: 1
  roles:
  - rhel_subscribe
  - sync_keys
  - install_repos
  - install_certs

- hosts: openshift_cloud
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  gather_facts: no
  roles:
  - sync_keys

- hosts: openshift_cloud
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - setup_ansible_host