---
- hosts: openstack-server
  vars:
  remote_user: justin
  become: yes
  become_method: sudo
  tasks:
  - name: create project
    os_project:
      cloud: default
      endpoint_type: admin
      state: present
      name: openshift
      description: "Let's host Openshift"

  - name: create user
    os_user:
      state: present
      cloud: default
      endpoint_type: admin
      domain: default
      name: openshift
      password: openshift
      default_project: openshift

  - name: copy public key to openstack server to keep shade happy
    copy:
      src: /Users/jusdavis/.ssh/id_rsa.pub
      dest: /root/openshift.pub
      owner: root
      group: root
      mode: 0600

  - name: add a key pair
    os_keypair:
      cloud: default
      state: present
      name: openshift_key
      public_key_file: /root/openshift.pub