---
- hosts: openstack-server
  vars:
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - setup_project
  - setup_network
  - { role: setup_server, server_name: "{{ project }}-master", image_name: "{{ app_image_name }}", server_flavour: "m1.small", docker_vol_size: 10}
  - { role: setup_server, server_name: "{{ project }}-infra", image_name: "{{ app_image_name }}", server_flavour: "m1.small", docker_vol_size: 10}
  - { role: setup_server, server_name: "{{ project }}-node1", image_name: "{{ app_image_name }}", server_flavour: "m1.large", docker_vol_size: 50}
  - { role: setup_server, server_name: "{{ project }}-node2", image_name: "{{ app_image_name }}", server_flavour: "m1.large", docker_vol_size: 50}