---
- hosts: openshift-servers
  vars:
  remote_user: "{{ app_remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - sync_keys

- hosts: openshift-servers
  vars:
  remote_user: "root"
  gather_facts: no
  roles:
  - sync_keys