---
- hosts: openstack-server
  vars:
    ports: []
  remote_user: "{{ remote_ssh_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
  - { role: teardown_server, server_name: "{{ project }}-node1"}
  - { role: teardown_server, server_name: "{{ project }}-node2"}
#  - { role: teardown_server, server_name: "{{ project }}-infra"}
  - { role: teardown_server, server_name: "{{ project }}-master"}
  - { role: teardown_server, server_name: "{{ project }}-ansible"}
  - teardown_network
  - teardown_project
