- name: install python2-pip
  yum:
    name: "python2-pip"
    state: latest

- name: install shade
  command: "pip install shade"
  register: result
- debug:
    var: result.stdout

- name: make home for clouds.yaml
  file:
    path: /root/.config/openstack
    state: directory
    mode: 0700

- name: install clouds.yaml
  copy:
   src: "{{ clouds_yaml }}"
   dest: /root/.config/openstack/clouds.yaml
   owner: root
   group: root
   mode: 0600