- name: install python2-pip
  yum:
    name: "python2-pip"
    state: latest

- name: install atomic-openshift-utils
  yum:
    name: atomic-openshift-utils
    state: latest

- name: gcc, python-devel
  yum:
    name: gcc, python-devel
    state: latest

- name: install shade
  command: "pip install shade"
  register: result
- debug:
    var: result.stdout

- name: make home for clouds.yaml
  file:
    path: /root/.config/openstack
    state: directory
    mode: 0700

- name: install clouds.yaml
  copy:
   src: "{{ clouds_yaml }}"
   dest: /root/.config/openstack/clouds.yaml
   owner: root
   group: root
   mode: 0600

- name: make home for scripts and inventory
  file:
    path: /root/bin/inventory
    state: directory
    mode: 0700


- name: install ansible
  yum:
    name: "ansible"
    state: latest

- name: python requests module
  easy_install:
    name: requests
    state: latest

- name: python urllib3 module
  easy_install:
    name: urllib3
    state: latest

- name: copy inventory
  copy:
   src: "hosts"
   dest: /root/bin/inventory/
   owner: root
   group: root
   mode: 0600

- name: copy inventory
  copy:
   src: "openstack.py"
   dest: /root/bin/inventory/
   owner: root
   group: root
   mode: 655

- name: copy install_ocp.sh
  copy:
   src: "install_ocp.sh"
   dest: /root/bin/
   owner: root
   group: root
   mode: 655