apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jupyter-tensorflow_gpu
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: tensorflow_gpu
    name: tensorflow_gpu
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tensorflow_gpu
      deploymentconfig: tensorflow_gpu
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: tensorflow_gpu
          deploymentconfig: tensorflow_gpu
      spec:
        serviceAccountName: privilegeduser
        containers:
        - name: tensorflow_gpu
          image: "tensorflow/tensorflow:latest-gpu"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["jupyter"]
          args: ["notebook", "--allow-root"]
          resources:
            limits:
              nvidia.com/gpu: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    name: tensorflow_gpu
    labels:
      app: tensorflow_gpu
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8888
    selector:
      app: tensorflow_gpu
    type: ClusterIP
    sessionAffinity: None
