---
- name: "create {{ project }} project"
  os_project:
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    state: present
    name: "{{ project }}"
    description: "Let's host {{ project }}"

- name: "create app user {{ app_user }}"
  os_user:
    state: present
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    domain: default
    name: "{{ app_user }}"
    password: "{{ app_user_password }}"
    default_project: "{{ project }}"

- name: "define app user {{ app_user }} roles"
  os_user_role:
    cloud: "{{ admin_cloud }}"
    user: "{{ app_user }}"
    role: "{{ app_user_role }}"
    project: "{{ project }}"
    endpoint_type: admin

- name: "define admin user roles"
  os_user_role:
    cloud: "{{ admin_cloud }}"
    user: admin
    role: admin
    project: "{{ project }}"
    endpoint_type: admin

- name: copy public key to openstack server to keep shade happy
  copy:
   src: "{{ public_key }}"
   dest: "{{ remote_public_key }}"
   owner: root
   group: root
   mode: 0600

- name: add a key pair
  os_keypair:
    cloud: "{{ app_cloud }}"
    state: present
    name: "{{ app_public_key }}"
    public_key_file: "{{ remote_public_key }}"

#- name: copy image to openstack server to keep shade happy
#  copy:
#   src: "{{ local_image }}"
#   dest: "{{ remote_image }}"
#   owner: root
#   group: root
#   mode: 0600
#
#- name: add an image
#  os_image:
#    cloud: "{{ app_cloud }}"
#    name: "{{ app_image_name }}"
#    container_format: bare
#    disk_format: "{{ image_format }}"
#    state: present
#    filename: "{{ remote_image }}"
#    wait: yes

- name: "Create '{{ project }}.bastion' flavor with {{ flavor_bastion_ram }}MB RAM, {{ flavor_bastion_vcpus }} vcpuss, and a {{ flavor_bastion_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.bastion"
    ram: "{{ flavor_bastion_ram }}"
    vcpus: "{{ flavor_bastion_vcpus }}"
    disk: "{{ flavor_bastion_disk }}"

- name: "Create '{{ project }}.node' flavor with {{ flavor_node_ram }}MB RAM, {{ flavor_node_vcpus }} vcpuss, and a {{ flavor_node_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.node"
    ram: "{{ flavor_node_ram }}"
    vcpus: "{{ flavor_node_vcpus }}"
    disk: "{{ flavor_node_disk }}"

- name: "Create '{{ project }}.master' flavor with {{ flavor_master_ram }}MB RAM, {{ flavor_master_vcpus }} vcpuss, and a {{ flavor_master_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.master"
    ram: "{{ flavor_master_ram }}"
    vcpus: "{{ flavor_master_vcpus }}"
    disk: "{{ flavor_master_disk }}"

- name: "Create '{{ project }}.infra' flavor with {{ flavor_infra_ram }}MB RAM, {{ flavor_infra_vcpus }} vcpuss, and a {{ flavor_infra_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.infra"
    ram: "{{ flavor_infra_ram }}"
    vcpus: "{{ flavor_infra_vcpus }}"
    disk: "{{ flavor_infra_disk }}"

- name: "Create '{{ project }}.lb' flavor with {{ flavor_lb_ram }}MB RAM, {{ flavor_lb_vcpus }} vcpuss, and a {{ flavor_lb_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.lb"
    ram: "{{ flavor_lb_ram }}"
    vcpus: "{{ flavor_lb_vcpus }}"
    disk: "{{ flavor_lb_disk }}"

- name: "Create '{{ project }}.nfs' flavor with {{ flavor_nfs_ram }}MB RAM, {{ flavor_nfs_vcpus }} vcpuss, and a {{ flavor_nfs_disk }}GB disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.nfs"
    ram: "{{ flavor_nfs_ram }}"
    vcpus: "{{ flavor_nfs_vcpus }}"
    disk: "{{ flavor_nfs_disk }}"

