---
- name: "create {{ project }} project"
  os_project:
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    state: present
    name: "{{ project }}"
    description: "Let's host {{ project }}"

- name: "create app user {{ app_user }}"
  os_user:
    state: present
    cloud: "{{ admin_cloud }}"
    endpoint_type: admin
    domain: default
    name: "{{ app_user }}"
    password: "{{ app_user_password }}"
    default_project: "{{ project }}"

- name: "define app user {{ app_user }} roles"
  os_user_role:
    cloud: "{{ admin_cloud }}"
    user: "{{ app_user }}"
    role: "{{ app_user_role }}"
    project: "{{ project }}"
    endpoint_type: admin

- name: "define admin user roles"
  os_user_role:
    cloud: "{{ admin_cloud }}"
    user: admin
    role: admin
    project: "{{ project }}"
    endpoint_type: admin

- name: copy public key to openstack server to keep shade happy
  copy:
   src: "{{ public_key }}"
   dest: "{{ remote_public_key }}"
   owner: root
   group: root
   mode: 0600

- name: add a key pair
  os_keypair:
    cloud: "{{ app_cloud }}"
    state: present
    name: "{{ app_public_key }}"
    public_key_file: "{{ remote_public_key }}"

- name: copy image to openstack server to keep shade happy
  copy:
   src: "{{ local_image }}"
   dest: "{{ remote_image }}"
   owner: root
   group: root
   mode: 0600

- name: add an image
  os_image:
    cloud: "{{ app_cloud }}"
    name: "{{ app_image_name }}"
    container_format: bare
    disk_format: "{{ image_format }}"
    state: present
    filename: "{{ remote_image }}"
    wait: yes

- name: "Create '{{ project }}.standard' flavor with 8GB of RAM, 2 virtual CPUs, and a 50GB local disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.standard"
    ram: 8096
    vcpus: 2
    disk: 50

- name: "Create '{{ project }}.node' flavor with 16GB of RAM, 4 virtual CPUs, and a 50GB local disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.node"
    ram: 16384
    vcpus: 4
    disk: 50

- name: "Create '{{ project }}.ansible' flavor with 2GB of RAM, 2 virtual CPUs, and a 20GB local disk"
  os_nova_flavor:
    cloud: "{{ admin_cloud }}"
    state: present
    name: "{{project }}.ansible"
    ram: 8096
    vcpus: 2
    disk: 20