apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "XXXX"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/kube_volumes/XXXX"
