- file:
    path: /tmp/myhosts
    state: touch
  delegate_to: localhost

- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ inventory_hostname }}"

- debug:
    msg: "{{ ansible_default_ipv4.address }}    {{ internal_hostname }}, {{ openstack_servers[0].public_v4 }}   {{ external_hostname }}"

- lineinfile:
    line: "{{ ansible_default_ipv4.address }}   {{ internal_hostname }}"
    path: /tmp/myhosts
  delegate_to: localhost

- lineinfile:
    line: "{{ openstack_servers[0].public_v4 }}   {{ external_hostname }}"
    path: /tmp/myhosts
  delegate_to: localhost
