- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ inventory_hostname }}"

- debug:
    msg: "{{ ansible_default_ipv4.address }}    {{ internal_hostname }}, {{ openstack_servers[0].public_v4 }}   {{ external_hostname }}"

- set_fact:
    etchosts: "{{ etchosts + [ansible_default_ipv4.address] }}"
    cacheable: true

- set_fact:
    etchosts: "{{ etchosts + [openstack_servers[0].public_v4] }}"
    cacheable: true

- debug:
    var: etchosts
