- name: getting IP addresses
  debug:
    msg: "{{ inventory_hostname }}: private: {{ ansible_default_ipv4.address }}"

# Gather facts about all servers named C<web*>:
- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ openstack_name }}"

- debug:
    var: "{{ openstack_servers.public_v4 }}"
