- name: getting IP addresses
  debug:
    msg: "{{ inventory_hostname }}: private: {{ ansible_default_ipv4.address }}"

# Gather facts about all servers named C<web*>:
- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ inventory_hostname }}"
  register: server_facts
- debug:
    var: server_facts
