- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ inventory_hostname }}"

- debug:
    msg: "{{ ansible_default_ipv4.address }}    {{ internal_hostname }}, {{ openstack_servers[0].public_v4 }}   {{ external_hostname }}"

- copy:
    content: "{{ ansible_default_ipv4.address }}    {{ internal_hostname }}\n"
    dest: myhosts
  delegate_to: localhost
  run_once: true

- copy:
    content: "{{ openstack_servers[0].public_v4 }}   {{ external_hostname }}\n"
    dest: myhosts
  delegate_to: localhost
  run_once: true
