- os_server_facts:
    cloud: "{{ app_cloud }}"
    server: "{{ inventory_hostname }}"

- debug:
    msg: "{{ ansible_default_ipv4.address }}    {{ inventory_hostname }}\n{{ openstack_servers[0].public_v4 }}   {{ inventory_hostname }}"
